import { PICKUP_RATES, computeQuote, estimateJobMinutes, type SizeTier } from "../pricing/computeQuote";
import { SERVICE_ZONE_ZIPS } from "../pricing/zone";
import { chicagoDate } from "../pricing/clock";
import type { DemoState } from "./types";

export const DEMO_SCHEMA_VERSION = 4;

export const DEMO_IDS = {
  admin: "a0000000-0000-4000-8000-000000000001",
  customer: "b0000000-0000-4000-8000-000000000002",
  driver: "c0000000-0000-4000-8000-000000000003",
  pendingDriver: "c0000000-0000-4000-8000-000000000013",
  openJob: "d0000000-0000-4000-8000-000000000010",
  activeJob: "d0000000-0000-4000-8000-000000000011",
  dropoffJob: "d0000000-0000-4000-8000-000000000012",
  paidTable: "d0000000-0000-4000-8000-000000000014",
  paidMattress: "d0000000-0000-4000-8000-000000000015",
  disputedJob: "d0000000-0000-4000-8000-000000000016",
  dispute: "e0000000-0000-4000-8000-000000000021",
  partner: "c0000000-0000-4000-8000-000000000014",
  sam: "c0000000-0000-4000-8000-000000000015",
  fridgeOpen: "d0000000-0000-4000-8000-000000000017",
  truckloadOpen: "d0000000-0000-4000-8000-000000000018",
  mobileOpen: "d0000000-0000-4000-8000-000000000019",
  paidDuo: "d0000000-0000-4000-8000-00000000001a",
} as const;

const VEHICLES = [
  ["pickup", 4500, 250, 5500],
  ["cargo_van", 5500, 300, 7000],
  ["box_truck", 8500, 400, 11000],
  ["flatbed", 9500, 450, 12500],
] as const;

const SIZES = [
  ["small", 1],
  ["medium", 1.15],
  ["large", 1.35],
  ["xl", 1.6],
] as const;

function user(id: string, role: string, name: string, phone: string, now: string) {
  return {
    id,
    role,
    display_name: name,
    phone,
    avatar_url: null,
    stripe_customer_id: null,
    created_at: now,
    updated_at: now,
  };
}

export function createDemoState(now = new Date().toISOString()): DemoState {
  const rules = VEHICLES.flatMap(([vehicle, base, perMile, min]) =>
    SIZES.map(([size, mult]) => ({
      id: `rule-${vehicle}-${size}`,
      market: "pensacola",
      vehicle_type: vehicle,
      size_category: size,
      base_cents: base,
      per_mile_cents: perMile,
      min_cents: min,
      size_multiplier: mult,
      active: true,
      effective_from: now,
    })),
  );

  return {
    schema_version: DEMO_SCHEMA_VERSION,
    users: [
      user(DEMO_IDS.admin, "admin", "Dominick", "8505550100", now),
      user(DEMO_IDS.customer, "customer", "Dana R.", "8505550101", now),
      user(DEMO_IDS.driver, "driver", "Marcus T.", "8505550102", now),
      user(DEMO_IDS.pendingDriver, "driver", "Tanya B.", "8505550103", now),
      user(DEMO_IDS.partner, "driver", "Dee P.", "8505550199", now),
      user(DEMO_IDS.sam, "driver", "Sam N.", "8505550198", now),
    ],
    customer_profiles: [
      {
        user_id: DEMO_IDS.customer,
        default_address: "21 E Government St, Pensacola, FL",
        default_lat: 30.4088,
        default_lng: -87.2166,
        rating_avg: 4.9,
        rating_count: 2,
      },
    ],
    driver_profiles: [
      {
        user_id: DEMO_IDS.driver,
        status: "approved",
        vehicle_type: "pickup",
        capacity_lbs: 1500,
        bed_length_ft: 6,
        service_lat: 30.4213,
        service_lng: -87.2169,
        service_radius_miles: 25,
        stripe_connect_account_id: null,
        rating_avg: 5,
        rating_count: 2,
        plate: "QXT 482",
        vehicle_make: "Ford",
        vehicle_model: "F-150",
        vehicle_color: "Silver",
        service_zip: "32502",
        is_online: true,
        current_lat: 30.4213,
        current_lng: -87.2169,
        last_seen_at: now,
        show_name_in_feed: true,
      },
      {
        user_id: DEMO_IDS.pendingDriver,
        status: "pending",
        vehicle_type: "cargo_van",
        capacity_lbs: 2000,
        bed_length_ft: 8,
        service_lat: 30.4213,
        service_lng: -87.2169,
        service_radius_miles: 20,
        stripe_connect_account_id: null,
        rating_avg: 0,
        rating_count: 0,
        plate: null,
        vehicle_make: "Ram",
        vehicle_model: "ProMaster",
        vehicle_color: "White",
        service_zip: "32503",
        is_online: false,
        current_lat: null,
        current_lng: null,
        last_seen_at: null,
        show_name_in_feed: false,
      },
      {
        user_id: DEMO_IDS.partner,
        status: "approved",
        vehicle_type: null,
        partner_only: true,
        capacity_lbs: null,
        bed_length_ft: null,
        service_lat: null,
        service_lng: null,
        service_radius_miles: 0,
        stripe_connect_account_id: "acct_demo_dee",
        background_check_at: now,
        background_check_by: DEMO_IDS.admin,
        rating_avg: 0,
        rating_count: 0,
        plate: null,
        vehicle_make: null,
        vehicle_model: null,
        vehicle_color: null,
        service_zip: null,
        is_online: true,
        current_lat: null,
        current_lng: null,
        last_seen_at: now,
        show_name_in_feed: false,
      },
      {
        user_id: DEMO_IDS.sam,
        status: "approved",
        vehicle_type: "pickup",
        partner_only: false,
        capacity_lbs: 1200,
        bed_length_ft: 6,
        service_lat: 30.4213,
        service_lng: -87.2169,
        service_radius_miles: 25,
        stripe_connect_account_id: null,
        background_check_at: now,
        background_check_by: DEMO_IDS.admin,
        rating_avg: 0,
        rating_count: 0,
        plate: "SAM 198",
        vehicle_make: "Toyota",
        vehicle_model: "Tacoma",
        vehicle_color: "Blue",
        service_zip: "32503",
        is_online: true,
        current_lat: 30.42,
        current_lng: -87.22,
        last_seen_at: now,
        show_name_in_feed: false,
      },
    ],
    jobs: [
      job(DEMO_IDS.openJob, "open", "Dresser", 30.4088, -87.2166, "21 E Government St, Pensacola, FL", 30.4758, -87.208, "5100 N 9th Ave, Pensacola, FL", null, 7000, now, "furniture"),
      job(DEMO_IDS.activeJob, "en_route_pickup", "Couch", 30.436, -87.191, "1200 E Gadsden St, Pensacola, FL", 30.4758, -87.208, "5100 N 9th Ave, Pensacola, FL", DEMO_IDS.driver, 10200, now, "couch"),
      pricedJob(DEMO_IDS.dropoffJob, "at_dropoff", "Fridge", "appliance_fridge", "large", 8, true, true, 0, 0, true, DEMO_IDS.driver, now, "32506", "32502", DEMO_IDS.partner),
      job(DEMO_IDS.paidTable, "paid", "Dining table", 30.4088, -87.2166, "21 E Government St, Pensacola, FL", 30.436, -87.191, "1200 E Gadsden St, Pensacola, FL", DEMO_IDS.driver, 7000, now, "furniture"),
      job(DEMO_IDS.paidMattress, "paid", "Mattress", 30.4758, -87.208, "5100 N 9th Ave, Pensacola, FL", 30.421, -87.283, "4100 W Fairfield Dr, Pensacola, FL", DEMO_IDS.driver, 12000, now, "mattress"),
      job(DEMO_IDS.disputedJob, "disputed", "Bookshelf", 30.4733, -87.1867, "2430 Airport Blvd, Pensacola, FL", 30.4088, -87.2166, "21 E Government St, Pensacola, FL", DEMO_IDS.driver, 8800, now, "furniture"),
      pricedJob(DEMO_IDS.fridgeOpen, "open", "Fridge", "appliance_fridge", "large", 8, true, true, 0, 0, true, null, now, "32502", "32503"),
      pricedJob(DEMO_IDS.truckloadOpen, "open", "Room of furniture", "moving_out", "truckload", 5, true, true, 0, 0, false, null, now, "32502", "32514"),
      pricedJob(DEMO_IDS.mobileOpen, "open", "Couch to Mobile", "couch", "medium", 60, true, false, 0, 0, false, null, now, "32502", "36602"),
      pricedJob(DEMO_IDS.paidDuo, "paid", "Fridge delivery", "appliance_fridge", "large", 8, true, true, 0, 0, true, DEMO_IDS.driver, now, "32502", "32506", DEMO_IDS.partner),
    ],
    job_events: [
      event("ev-open", DEMO_IDS.openJob, "open", DEMO_IDS.customer, now, { seed: "demo" }),
      event("ev-active", DEMO_IDS.activeJob, "en_route_pickup", DEMO_IDS.driver, now, { from: "assigned", to: "en_route_pickup", seed: "demo" }),
      event("ev-drop", DEMO_IDS.dropoffJob, "at_dropoff", DEMO_IDS.driver, now, { from: "en_route_dropoff", to: "at_dropoff", seed: "demo" }),
      event("ev-paid-1", DEMO_IDS.paidTable, "paid", DEMO_IDS.driver, now, { seed: "demo" }),
      event("ev-paid-2", DEMO_IDS.paidMattress, "paid", DEMO_IDS.driver, now, { seed: "demo" }),
      event("ev-dispute", DEMO_IDS.disputedJob, "disputed", DEMO_IDS.customer, now, { previous_status: "delivered", seed: "demo" }),
    ],
    job_photos: [],
    disputes: [
      {
        id: DEMO_IDS.dispute,
        job_id: DEMO_IDS.disputedJob,
        opened_by: DEMO_IDS.customer,
        reason: "The drop-off didn't match what was booked.",
        status: "open",
        resolution_notes: null,
        resolved_by: null,
        resolved_at: null,
        created_at: now,
      },
    ],
    payouts: [
      payout("po-1", DEMO_IDS.paidTable, 5950, now, DEMO_IDS.driver, "lead"),
      payout("po-2", DEMO_IDS.paidMattress, 10200, now, DEMO_IDS.driver, "lead"),
      payout("po-duo-lead", DEMO_IDS.paidDuo, 8075, now, DEMO_IDS.driver, "lead"),
      payout("po-duo-partner", DEMO_IDS.paidDuo, 3825, now, DEMO_IDS.partner, "partner"),
    ],
    pricing_rules: rules,
    ratings: [],
    device_tokens: [],
    driver_documents: [
      doc("doc-lic", DEMO_IDS.driver, "license", "approved", now),
      doc("doc-ins", DEMO_IDS.driver, "insurance", "approved", now),
      doc("doc-photo", DEMO_IDS.driver, "vehicle_photo", "approved", now),
      doc("doc-tanya-lic", DEMO_IDS.pendingDriver, "license", "in_review", now),
      doc("doc-dee-lic", DEMO_IDS.partner, "license", "approved", now),
      doc("doc-dee-photo", DEMO_IDS.partner, "profile_photo", "approved", now),
      doc("doc-sam-lic", DEMO_IDS.sam, "license", "approved", now),
    ],
    feed_posts: [
      feedPost("feed-couch", DEMO_IDS.paidTable, "Large couch", "Large", "couch", "large", "Cordova Park", "East Hill", "September", "photo-couch-before", "photo-couch-after", now),
      feedPost("feed-fridge", DEMO_IDS.paidMattress, "Medium fridge", "Medium", "appliance", "medium", "Brownsville", "Downtown", "September", "photo-fridge-before", "photo-fridge-after", now),
      feedPost("feed-mattress", DEMO_IDS.disputedJob, "Medium mattress", "Medium", "mattress", "medium", "Myrtle Grove", "North Hill", "August", "photo-mattress-before", "photo-mattress-after", now),
    ],
    driver_partnerships: [
      {
        id: "part-ended",
        lead_id: DEMO_IDS.driver,
        partner_id: DEMO_IDS.partner,
        shift_date: chicagoDate(new Date(new Date(now).getTime() - 36 * 60 * 60 * 1000)),
        status: "ended",
        invited_at: now,
        responded_at: now,
        ended_at: now,
        ended_by: DEMO_IDS.driver,
      },
    ],
    service_zone_zips: SERVICE_ZONE_ZIPS.map((zip) => ({ market: "pensacola", zip })),
    rate_cards: [
      {
        id: "rate-pickup-2026-09-24",
        market: "pensacola",
        vehicle_type: "pickup",
        rates_version: PICKUP_RATES.ratesVersion,
        active: true,
        base_cents: PICKUP_RATES.baseCents,
        per_mile_cents: PICKUP_RATES.perMileCents,
        min_fare_cents: PICKUP_RATES.minFareCents,
        platform_fee_bps: PICKUP_RATES.platformFeeBps,
        stairs_per_flight_cents: PICKUP_RATES.stairsPerFlightCents,
        second_person_per_hour_cents: PICKUP_RATES.secondPersonPerHourCents,
        second_person_min_cents: PICKUP_RATES.secondPersonMinCents,
        second_person_step_cents: PICKUP_RATES.secondPersonStepCents,
        out_of_town_per_mile_cents: PICKUP_RATES.outOfTownPerMileCents,
        max_loaded_miles: PICKUP_RATES.maxLoadedMiles,
        max_flights_per_stop: PICKUP_RATES.maxFlightsPerStop,
        est_deadhead_miles: PICKUP_RATES.estDeadheadMiles,
        est_city_min_per_mile: PICKUP_RATES.estCityMinPerMile,
        est_highway_min_per_mile: PICKUP_RATES.estHighwayMinPerMile,
        est_highway_after_miles: PICKUP_RATES.estHighwayAfterMiles,
        est_admin_minutes: PICKUP_RATES.estAdminMinutes,
        est_minutes_per_flight: PICKUP_RATES.estMinutesPerFlight,
      },
    ],
    size_tier_rates: (Object.keys(PICKUP_RATES.sizeTierAddonCents) as SizeTier[]).map((tier) => ({
      rate_card_id: "rate-pickup-2026-09-24",
      size_tier: tier,
      addon_cents: PICKUP_RATES.sizeTierAddonCents[tier],
      est_load_minutes: PICKUP_RATES.estLoadMinutes[tier],
    })),
  };
}

function doc(id: string, driverId: string, kind: string, status: string, now: string) {
  return {
    id,
    driver_id: driverId,
    kind,
    storage_path: `${driverId}/${kind}.jpg`,
    status,
    note: null,
    created_at: now,
    reviewed_at: status === "approved" ? now : null,
    reviewed_by: status === "approved" ? DEMO_IDS.admin : null,
  };
}

function job(
  id: string,
  status: string,
  item: string,
  pickupLat: number,
  pickupLng: number,
  pickup: string,
  dropLat: number,
  dropLng: number,
  dropoff: string,
  driverId: string | null,
  cents: number,
  now: string,
  itemType = "furniture",
) {
  const fee = Math.round(cents * 0.15);
  return {
    id,
    customer_id: DEMO_IDS.customer,
    driver_id: driverId,
    status,
    pickup_address: pickup,
    pickup_lat: pickupLat,
    pickup_lng: pickupLng,
    pickup_notes: item === "Couch" ? "Gate code 4412" : null,
    dropoff_address: dropoff,
    dropoff_lat: dropLat,
    dropoff_lng: dropLng,
    dropoff_notes: null,
    item_description: item,
    item_type: itemType,
    size_category: itemType === "couch" ? "medium" : "medium",
    size_tier: itemType === "couch" ? "medium" : "medium",
    vehicle_required: "pickup",
    stairs_pickup_flights: 0,
    stairs_dropoff_flights: 0,
    needs_second_person: false,
    weight_band: null,
    billable_miles: 5,
    distance_source: "demo",
    est_job_minutes: 60,
    rates_version: PICKUP_RATES.ratesVersion,
    quoted_at: now,
    pickup_zip: "32502",
    dropoff_zip: "32503",
    pickup_in_zone: true,
    dropoff_in_zone: true,
    driver_share_cents: cents - fee,
    lead_payout_cents: cents - fee,
    helper_payout_cents: 0,
    partner_driver_id: null,
    partner_lost_at: null,
    dropoff_placement: "inside",
    quote_lines: null,
    distance_miles: 4.5,
    estimate_cents: cents,
    final_cents: cents,
    platform_fee_cents: fee,
    driver_payout_cents: cents - fee,
    stripe_payment_intent_id: status === "draft" || status === "priced" ? null : `pi_sandbox_demo_${id.slice(0, 8)}`,
    scheduled_at: null,
    accepted_at: driverId ? now : null,
    picked_up_at: null,
    delivered_at: status === "paid" || status === "disputed" ? now : null,
    cancelled_at: null,
    cancel_reason: null,
    created_at: now,
    updated_at: now,
  };
}

function event(id: string, jobId: string, type: string, actor: string, now: string, payload: Record<string, unknown>) {
  return { id, job_id: jobId, type, actor_id: actor, payload, created_at: now };
}

function feedPost(
  id: string,
  jobId: string,
  item: string,
  size: string,
  itemType: string,
  sizeCategory: string,
  pickup: string,
  dropoff: string,
  month: string,
  before: string,
  after: string,
  now: string,
) {
  return {
    id,
    job_id: jobId,
    status: "approved",
    is_demo: true,
    item_label: item,
    size_label: size,
    item_type: itemType,
    size_category: sizeCategory,
    pickup_area: pickup,
    dropoff_area: dropoff,
    month_label: month,
    driver_name: "Marcus",
    rating_avg: 5,
    rating_count: 2,
    before_key: before,
    after_key: after,
    approved_by: DEMO_IDS.admin,
    created_at: now,
    updated_at: now,
  };
}

function payout(id: string, jobId: string, amount: number, now: string, driverId: string = DEMO_IDS.driver, role: "lead" | "partner" = "lead") {
  return {
    id,
    job_id: jobId,
    driver_id: driverId,
    amount_cents: amount,
    status: "pending",
    role,
    created_at: now,
  };
}

function pricedJob(
  id: string,
  status: string,
  item: string,
  itemType: string,
  tier: SizeTier,
  roadMiles: number,
  pickupInZone: boolean,
  dropoffInZone: boolean,
  pickupFlights: number,
  dropoffFlights: number,
  secondPerson: boolean,
  driverId: string | null,
  now: string,
  pickupZip: string,
  dropoffZip: string,
  partnerId: string | null = null,
) {
  const minutes = estimateJobMinutes({
    roadMiles,
    pickupInZone,
    dropoffInZone,
    sizeTier: tier,
    pickupFlights,
    dropoffFlights,
  });
  const quote = computeQuote({
    sizeTier: tier,
    roadMiles,
    distanceSource: "maps",
    pickupInZone,
    dropoffInZone,
    pickupFlights,
    dropoffFlights,
    secondPerson,
    estJobHours: minutes / 60,
    vehicleType: "pickup",
  });
  const base = job(id, status, item, 30.4088, -87.2166, "21 E Government St, Pensacola, FL", dropoffZip === "36602" ? 30.6954 : 30.4758, dropoffZip === "36602" ? -88.0399 : -87.208, dropoffZip === "36602" ? "150 Government St, Mobile, AL" : "5100 N 9th Ave, Pensacola, FL", driverId, quote.totalCents, now, itemType);
  return {
    ...base,
    size_category: tier,
    size_tier: tier,
    needs_second_person: quote.lines.some((line) => line.code === "second_person"),
    stairs_pickup_flights: pickupFlights,
    stairs_dropoff_flights: dropoffFlights,
    distance_miles: roadMiles,
    billable_miles: quote.billableMiles,
    estimate_cents: quote.totalCents,
    final_cents: quote.totalCents,
    platform_fee_cents: quote.platformFeeCents,
    driver_share_cents: quote.driverShareCents,
    driver_payout_cents: quote.leadDriverKeepsCents,
    lead_payout_cents: quote.leadDriverKeepsCents,
    helper_payout_cents: quote.helperShareCents,
    quote_lines: quote.lines,
    est_job_minutes: minutes,
    pickup_zip: pickupZip,
    dropoff_zip: dropoffZip,
    pickup_in_zone: pickupInZone,
    dropoff_in_zone: dropoffInZone,
    partner_driver_id: partnerId,
    pickup_notes: null,
    distance_source: "demo",
  };
}
